version: '3.4'

services:
  nginx:
    image: nginx:1.17.1-alpine
    ports:
    - "5000:80"
    volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d
    - ./nginx/html:/usr/share/nginx/html
  registry:
    image: registry:2.7.1
    volumes:
    - ./registry:/var/lib/registry
